Create а dataframe

In [13]:
import pandas as pd

views = pd.read_csv(
    '../data/feed-views.log',
    sep='\t',
    names=['datetime', 'user']
)

views.head()

                     datetime   user
0  2020-04-17 12:01:08.463179  artem
1  2020-04-17 12:01:23.743946  artem
2  2020-04-17 12:27:30.646665  artem
3  2020-04-17 12:35:44.884757  artem
4  2020-04-17 12:35:52.735016  artem

Convert datetime type

In [14]:
views['datetime']=pd.to_datetime(views['datetime'])
views.dtypes

datetime    datetime64[ns]
user                object
dtype: object

Extract date and time parts

In [15]:
views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views['day'] = views['datetime'].dt.day
views['hour'] = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

views.head()

                    datetime   user  year  month  day  hour  minute  second
0 2020-04-17 12:01:08.463179  artem  2020      4   17    12       1       8
1 2020-04-17 12:01:23.743946  artem  2020      4   17    12       1      23
2 2020-04-17 12:27:30.646665  artem  2020      4   17    12      27      30
3 2020-04-17 12:35:44.884757  artem  2020      4   17    12      35      44
4 2020-04-17 12:35:52.735016  artem  2020      4   17    12      35      52

Create the daytime column

In [20]:
bins = [-1, 3, 6, 10, 16, 19, 23]

labels = [
    'night',
    'early morning',
    'morning',
    'afternoon',
    'early evening',
    'evening'
]

views['daytime'] = pd.cut(
    views['hour'],
    bins=bins,
    labels=labels
)

views[['hour', 'daytime']].head()

   hour    daytime
0    12  afternoon
1    12  afternoon
2    12  afternoon
3    12  afternoon
4    12  afternoon

Set user as the index

In [21]:
views=views.set_index('user')
views.head()

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon

Count the number of elements

In [24]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

value_counts

In [30]:
views['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

Sort the values by hour, minute, and second

In [48]:
views=views.sort_values(by=['hour', 'minute', 'second'])
views.head(8)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
valentina,2020-05-15 00:02:05.652585,2020,5,15,0,2,5,night
alexander,2020-05-15 00:05:27.798227,2020,5,15,0,5,27,night
artem,2020-04-20 00:08:17.652510,2020,4,20,0,8,17,night

Calculate the minimum and maximum hours and the mode for daytime

In [34]:
min_hour = views['hour'].min()
max_hour = views['hour'].max()
mode_daytime = views['daytime'].mode()

min_hour, max_hour, mode_daytime

(np.int32(0),
 np.int32(23),
 0    evening
 Name: daytime, dtype: category
 Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening'])

Calculate the maximum hour for the rows where time for days is morning

In [36]:
min_morning_hour = views[views['daytime'] == 'morning']['hour'].min()

min_morning_hour

np.int32(8)

Calculate the maximum hour for night rows

In [38]:
max_night_hour = views[views['daytime'] == 'night']['hour'].max()

max_night_hour

np.int32(3)

Find who visited the page during those hours

In [43]:
night_example = views[
    (views['daytime'] == 'night') &
    (views['hour'] == max_night_hour)
].head(1)

night_example

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night

In [42]:
morning_example = views[
    (views['daytime'] == 'morning') &
    (views['hour'] == min_morning_hour)
].head(1)

morning_example

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning

Calculate the mode for hour and daytime

In [49]:
mode_hour = views['hour'].mode()
mode_daytime = views['daytime'].mode()

mode_hour, mode_daytime

(0    22
 Name: hour, dtype: int32,
 0    evening
 Name: daytime, dtype: category
 Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening'])

Show the three earliest hours with corresponding usernames

In [50]:
views.nsmallest(3, 'hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night

Show the three latest hours with corresponding usernames

In [51]:
views.nlargest(3,'hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
ekaterina,2020-05-14 23:02:11.327532,2020,5,14,23,2,11,evening
ekaterina,2020-05-14 23:02:14.494985,2020,5,14,23,2,14,evening
ekaterina,2020-05-14 23:02:15.588808,2020,5,14,23,2,15,evening

Find the most popular visiting interval

In [58]:
desc=views.describe()

iqr=desc.loc['75%','hour']-desc.loc['25%','hour']

iqr, desc

(np.float64(9.0),
                             datetime    year        month          day  \
 count                           1076  1076.0  1076.000000  1076.000000
 mean   2020-05-10 09:00:41.211420672  2020.0     4.870818    13.552974
 min       2020-04-17 12:01:08.463179  2020.0     4.000000     1.000000
 25%       2020-05-10 01:13:49.857472  2020.0     5.000000    11.000000
 50%    2020-05-11 22:48:35.302552832  2020.0     5.000000    13.000000
 75%    2020-05-14 14:44:34.749530624  2020.0     5.000000    15.000000
 max       2020-05-22 10:36:14.662600  2020.0     5.000000    30.000000
 std                              NaN     0.0     0.335557     4.906567

               hour       minute       second
 count  1076.000000  1076.000000  1076.000000
 mean     16.249071    29.629182    29.500929
 min       0.000000     0.000000     0.000000
 25%      13.000000    14.000000    14.000000
 50%      19.000000    29.000000    30.000000
 75%      22.000000    46.000000    45.000000
 max      23.000000    59.000000    59.000000
 std       6.955490    17.689388    17.405506  )